const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
const LOGIN_FAILURE = 'LOGIN_FAILURE'
const HANDLE_MESSAGE = 'HANDLE_MESSAGE'
const EMIT_MESSAGE = 'EMIT_MESSAGE'
const LOGIN_REQUEST = 'LOGIN_REQUEST'

module.exports = {
  LOGIN_FAILURE,
  LOGIN_SUCCESS,
  HANDLE_MESSAGE,
  EMIT_MESSAGE,
  LOGIN_REQUEST
}